AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for lambda-dotnetcore3.1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  GetPlantsForUserIdFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/GetPlantsForUserId/
      Handler: GetPlantsForUserId::GetPlantsForUserId.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        GetPlantsForUserId:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /GetPlantsForUserId
            Method: get
            RequestParameters: 
              - method.request.querystring.userid:
                  Required: true
                  Caching: false
  AddUserPlantFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/AddUserPlant/
      Handler: AddUserPlant::AddUserPlant.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        AddUserPlant:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /AddUserPlant
            Method: get
            RequestParameters: 
              - method.request.querystring.userid:
                  Required: true
                  Caching: false
              - method.request.querystring.plantDataId:
                  Required: true
                  Caching: false
              - method.request.querystring.plantName:
                  Required: true
                  Caching: false
              - method.request.querystring.plantLocation:
                  Required: true
                  Caching: false
              - method.request.querystring.windowLocation:
                  Required: false
                  Caching: false
              - method.request.querystring.lastWatered:
                  Required: false
                  Caching: false
  DeleteUserPlantFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/DeleteUserPlant/
      Handler: DeleteUserPlant::DeleteUserPlant.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        DeleteUserPlant:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /DeleteUserPlant
            Method: get
            RequestParameters: 
              - method.request.querystring.userPlantId:
                  Required: true
                  Caching: false
  GetAllPlantTypesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/GetAllPlantTypes/
      Handler: GetAllPlantTypes::GetAllPlantTypes.Function::FunctionHandler
      Runtime: dotnetcore3.1
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        GetAllPlantTypes:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /GetAllPlantTypes
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetPlantsForUserIdApi:
    Description: "API Gateway endpoint URL for Prod stage for GetPlantsForUserId function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/GetPlantsForUserId/"
  GetPlantsForUserIdFunction:
    Description: "GetPlantsForUserId ARN"
    Value: !GetAtt GetPlantsForUserIdFunction.Arn
  GetPlantsForUserIdFunctionIamRole:
    Description: "Implicit IAM Role created for GetPlantsForUserId function"
    Value: !GetAtt GetPlantsForUserIdFunctionRole.Arn
  AddUserPlantApi:
    Description: "API Gateway endpoint URL for Prod stage for AddUserPlant function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/AddUserPlant/"
  AddUserPlantFunction:
    Description: "AddUserPlant ARN"
    Value: !GetAtt AddUserPlantFunction.Arn
  AddUserPlantFunctionIamRole:
    Description: "Implicit IAM Role created for AddUserPlant function"
    Value: !GetAtt AddUserPlantFunctionRole.Arn
  GetAllPlantTypesApi:
    Description: "API Gateway endpoint URL for Prod stage for GetAllPlantTypes function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/GetAllPlantTypes/"
  GetAllPlantTypesFunction:
    Description: "GetAllPlantTypes ARN"
    Value: !GetAtt GetAllPlantTypesFunction.Arn
  GetAllPlantTypesFunctionIamRole:
    Description: "Implicit IAM Role created for GetAllPlantTypes function"
    Value: !GetAtt GetAllPlantTypesFunctionRole.Arn  
  DeleteUserPlantApi:
    Description: "API Gateway endpoint URL for Prod stage for DeleteUserPlant function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/DeleteUserPlant/"
  DeleteUserPlantFunction:
    Description: "DeleteUserPlant ARN"
    Value: !GetAtt DeleteUserPlantFunction.Arn
  DeleteUserPlantFunctionIamRole:
    Description: "Implicit IAM Role created for DeleteUserPlant function"
    Value: !GetAtt DeleteUserPlantFunctionRole.Arn  